name: demo
description: Flutter project setup demo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+2
  desktop_window: ^0.4.0
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/3.0x/logo_blue.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/3.0x/logo_blue.png"
    background_color: "#ffffffff"
    theme_color: "#4169E1"
  windows:
    generate: true
    image_path: "assets/images/3.0x/logo_blue.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/3.0x/logo_blue.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300


